//api1
GET http://localhost:3000/todos/?status=TO%20DO


//api 2
###
GET http://localhost:3000/todos/3/

//api 3
###
POST http://localhost:3000/todos/

//api 4
###
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
    "priority": "HIGH"
}

//api 5
###
DELETE http://localhost:3000/todos/1/